# Generated by Django 5.2.1 on 2026-03-12 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('tools', '0008_aicostlog_created_at_purchase_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPromptMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_text', models.TextField(help_text='Global anti-patterns and strict instructions for this specific client.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_memo', to='tools.client')),
            ],
        ),
        migrations.CreateModel(
            name='AccountMappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_keywords', models.CharField(help_text="e.g., 'Vital drinking water, Rice for worker'", max_length=500)),
                ('ai_guideline', models.TextField(help_text='Reasoning for the AI.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_rules', to='tools.client')),
            ],
            options={
                'unique_together': {('client', 'account')},
            },
        ),
    ]
