# Generated by Django 5.2.1 on 2026-03-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_clientpromptmemo_accountmappingrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
