# Generated by Django 5.2.1 on 2026-04-08 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_journalentry_description_and_more'),
        ('cash', '0006_bank_user_cash_user'),
        ('tools', '0017_remove_journalvoucher_credi_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='exclusive_source_document_constraint',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='tools.journalvoucher'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='tools.old'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', False)), models.Q(('bank__isnull', False), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', True)), models.Q(('bank__isnull', True), ('cash__isnull', False), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', True)), models.Q(('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', False), ('old__isnull', True), ('purchase__isnull', True)), models.Q(('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', False), ('purchase__isnull', True)), models.Q(('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', True)), _connector='OR'), name='exclusive_source_document_constraint'),
        ),
    ]
