# Generated by Django 5.2.1 on 2026-04-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_journalentry_exclusive_source_document_constraint_and_more'),
        ('tools', '0017_remove_journalvoucher_credi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpromptmemo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='clientpromptmemo',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General & Universal Rules'), ('BANK_EXTRACTION', 'Bank Statement Extraction'), ('RECONCILIATION', 'GL Mapping & Reconciliation'), ('PURCHASE', 'Purchase & Expense Rules')], default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientpromptmemo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.client'),
        ),
        migrations.AlterField(
            model_name='clientpromptmemo',
            name='memo_text',
            field=models.TextField(),
        ),
    ]
