# Generated by Django 5.2.1 on 2026-04-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_clientpromptmemo_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpromptmemo',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General & Universal Rules'), ('BANK_EXTRACTION', 'Bank Statement Extraction'), ('RECONCILIATION', 'GL Mapping & Reconciliation'), ('PURCHASE', 'Purchase & Expense Rules'), ('VENDOR_CUSTOMER', 'Vendor & Customer Rules')], default='GENERAL', max_length=50),
        ),
    ]
