# Generated by Django 5.2.1 on 2026-05-04 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_clientpromptmemo_category'),
        ('tools', '0021_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='tools.adjustment'),
        ),
    ]
