# Generated by Django 5.2.1 on 2026-05-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_journalentry_adjustment'),
        ('cash', '0011_bank_matched_jv_bank_matched_jv_ids_cash_matched_jv_and_more'),
        ('tools', '0021_adjustment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='exclusive_source_document_constraint',
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('adjustment__isnull', True), ('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', False)), models.Q(('adjustment__isnull', True), ('bank__isnull', False), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', True)), models.Q(('adjustment__isnull', True), ('bank__isnull', True), ('cash__isnull', False), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', True)), models.Q(('adjustment__isnull', True), ('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', False), ('old__isnull', True), ('purchase__isnull', True)), models.Q(('adjustment__isnull', True), ('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', False), ('purchase__isnull', True)), models.Q(('adjustment__isnull', False), ('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', True)), models.Q(('adjustment__isnull', True), ('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', True)), _connector='OR'), name='exclusive_source_document_constraint'),
        ),
    ]
