# Generated by Django 5.2.1 on 2026-05-28 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_accountmappingrule_unique_together_and_more'),
        ('assets', '0001_initial'),
        ('cash', '0012_remove_bank_client_remove_cash_client_historicalbank_and_more'),
        ('tools', '0024_remove_adjustment_client_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='exclusive_source_document_constraint',
        ),
        migrations.AddField(
            model_name='historicaljournalentry',
            name='asset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='assets.asset'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('adjustment__isnull', True), ('asset__isnull', True), ('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', False)), models.Q(('adjustment__isnull', True), ('asset__isnull', True), ('bank__isnull', False), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', True)), models.Q(('adjustment__isnull', True), ('asset__isnull', True), ('bank__isnull', True), ('cash__isnull', False), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', True)), models.Q(('adjustment__isnull', True), ('asset__isnull', True), ('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', False), ('old__isnull', True), ('purchase__isnull', True)), models.Q(('adjustment__isnull', True), ('asset__isnull', True), ('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', False), ('purchase__isnull', True)), models.Q(('adjustment__isnull', False), ('asset__isnull', True), ('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', True)), models.Q(('adjustment__isnull', True), ('asset__isnull', False), ('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', True)), models.Q(('adjustment__isnull', True), ('asset__isnull', True), ('bank__isnull', True), ('cash__isnull', True), ('journal_voucher__isnull', True), ('old__isnull', True), ('purchase__isnull', True)), _connector='OR'), name='exclusive_source_document_constraint'),
        ),
    ]
