# Generated by Django 5.2.1 on 2026-06-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_journalentry_exclusive_source_document_constraint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('period_label', models.CharField(help_text='e.g., May 2026 or YTD', max_length=50)),
                ('total_cash_usd', models.FloatField(default=0.0)),
                ('total_ar_usd', models.FloatField(default=0.0)),
                ('total_ap_usd', models.FloatField(default=0.0)),
                ('net_profit_usd', models.FloatField(default=0.0)),
                ('chart_data_payload', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
    ]
