# Generated by Django 5.2.1 on 2026-06-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_dashboardsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsnapshot',
            name='exchange_rate',
            field=models.IntegerField(blank=True, help_text='KHR to USD exchange rate', null=True),
        ),
    ]
