# Generated by Django 5.2.1 on 2026-06-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_dashboardsnapshot_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsnapshot',
            name='ai_executive_summary',
            field=models.TextField(blank=True, help_text='AI generated summary of the snapshot', null=True),
        ),
    ]
