# Generated by Django 5.2.1 on 2026-06-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_dashboardsnapshot_ai_executive_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('RECON', 'Reconciliation Agent ⚖️'), ('TAX', 'Tax & Compliance Agent 🏛️'), ('ECON', 'Macro-Economic Agent 📈'), ('AUDIT', 'Internal Audit Agent 🔍'), ('SYSTEM', 'System Operations ⚙️')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Informational (Blue)'), ('SUCCESS', 'Success (Green)'), ('WARNING', 'Warning / Action Needed (Yellow)'), ('CRITICAL', 'Critical / Blocking (Red)')], default='INFO', max_length=20)),
                ('title', models.CharField(help_text='e.g., Missing VAT TIN Detected', max_length=255)),
                ('message', models.TextField(help_text='The detailed explanation from the AI.')),
                ('action_url', models.CharField(blank=True, help_text='URL path to the relevant app view', max_length=500, null=True)),
                ('action_label', models.CharField(blank=True, help_text="e.g., 'Review Invoices'", max_length=50, null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Has the human or AI resolved this issue?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved', '-created_at'], name='account_age_is_reso_541fd6_idx')],
            },
        ),
    ]
