# Generated by Django 5.2.1 on 2026-06-11 08:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_agentnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKnowledgeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_scope', models.CharField(choices=[('GLOBAL', 'All Agents'), ('TAX', 'Tax & Compliance Agent'), ('RECON', 'Reconciliation Agent'), ('ECON', 'Macro-Economic Agent')], default='GLOBAL', max_length=20)),
                ('rule_type', models.CharField(choices=[('ACCOUNT_MAPPING', 'GL Account Mapping Rule'), ('TAX_LAW', 'Tax Compliance Law / Rate'), ('MACRO_FACT', 'Macro-Economic Insight / Fact'), ('ANTI_PATTERN', 'Common Mistake to Avoid')], max_length=20)),
                ('tags', models.CharField(help_text="Comma separated, e.g., 'WHT, rental, cambodia'", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='e.g., CAPEX IDENTIFICATION (FACTORY)', max_length=255)),
                ('condition', models.TextField(help_text="WHEN does this rule apply? (e.g., 'When invoice has construction materials')")),
                ('action_or_fact', models.TextField(help_text="WHAT should the AI do or know? (e.g., 'Classify as 181000 - Factory CIP')")),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAgentKnowledgeRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('agent_scope', models.CharField(choices=[('GLOBAL', 'All Agents'), ('TAX', 'Tax & Compliance Agent'), ('RECON', 'Reconciliation Agent'), ('ECON', 'Macro-Economic Agent')], default='GLOBAL', max_length=20)),
                ('rule_type', models.CharField(choices=[('ACCOUNT_MAPPING', 'GL Account Mapping Rule'), ('TAX_LAW', 'Tax Compliance Law / Rate'), ('MACRO_FACT', 'Macro-Economic Insight / Fact'), ('ANTI_PATTERN', 'Common Mistake to Avoid')], max_length=20)),
                ('tags', models.CharField(help_text="Comma separated, e.g., 'WHT, rental, cambodia'", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='e.g., CAPEX IDENTIFICATION (FACTORY)', max_length=255)),
                ('condition', models.TextField(help_text="WHEN does this rule apply? (e.g., 'When invoice has construction materials')")),
                ('action_or_fact', models.TextField(help_text="WHAT should the AI do or know? (e.g., 'Classify as 181000 - Factory CIP')")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical agent knowledge rule',
                'verbose_name_plural': 'historical agent knowledge rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
