# Generated by Django 5.2.1 on 2026-06-14 08:44

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_agentknowledgerule_historicalagentknowledgerule'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                EXECUTE 'CREATE EXTENSION IF NOT EXISTS vector';
                IF NOT EXISTS (
                    SELECT 1 FROM pg_extension e 
                    JOIN pg_namespace n ON n.oid = e.extnamespace 
                    WHERE e.extname = 'vector' AND n.nspname = 'public'
                ) THEN
                    EXECUTE 'ALTER EXTENSION vector SET SCHEMA public';
                END IF;
            END
            $$;
            """,
            reverse_sql="DROP EXTENSION IF EXISTS vector;"
        ),

        migrations.AddField(
            model_name='agentknowledgerule',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='historicalagentknowledgerule',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]