# Generated by Django 5.2.1 on 2026-06-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_agentknowledgerule_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentknowledgerule',
            name='priority_weight',
            field=models.IntegerField(default=10, help_text='Higher numbers override lower numbers during conflicts. (e.g., Exceptions = 100)'),
        ),
        migrations.AddField(
            model_name='historicalagentknowledgerule',
            name='priority_weight',
            field=models.IntegerField(default=10, help_text='Higher numbers override lower numbers during conflicts. (e.g., Exceptions = 100)'),
        ),
        migrations.AlterField(
            model_name='agentknowledgerule',
            name='rule_type',
            field=models.CharField(choices=[('ACCOUNT_MAPPING', 'GL Account Mapping Rule'), ('TAX_LAW', 'Tax Compliance Law / Rate'), ('MACRO_FACT', 'Macro-Economic Insight / Fact'), ('ANTI_PATTERN', 'Common Mistake to Avoid'), ('DOCUMENT_PARSING', 'OCR & Document Formatting Directive'), ('WORKFLOW_ROUTING', 'System Orchestration Rule')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalagentknowledgerule',
            name='rule_type',
            field=models.CharField(choices=[('ACCOUNT_MAPPING', 'GL Account Mapping Rule'), ('TAX_LAW', 'Tax Compliance Law / Rate'), ('MACRO_FACT', 'Macro-Economic Insight / Fact'), ('ANTI_PATTERN', 'Common Mistake to Avoid'), ('DOCUMENT_PARSING', 'OCR & Document Formatting Directive'), ('WORKFLOW_ROUTING', 'System Orchestration Rule')], max_length=20),
        ),
    ]
