# Generated by Django 5.2.1 on 2026-03-05 03:02

import document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_rename_uploaded_at_document_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(upload_to=document.models.generate_upload_path),
        ),
    ]
