# Generated by Django 5.2.1 on 2026-06-12 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_agentknowledgerule_historicalagentknowledgerule'),
        ('document', '0003_alter_document_id_alter_document_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Prakas No. 012 on WHT', max_length=255)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('document_pdf', models.FileField(upload_to='knowledge_sources/')),
                ('date_issued', models.DateField()),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DraftKnowledgeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_agent_scope', models.CharField(max_length=20)),
                ('proposed_title', models.CharField(max_length=255)),
                ('proposed_condition', models.TextField()),
                ('proposed_action_or_fact', models.TextField()),
                ('proposed_tags', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('promoted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.agentknowledgerule')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.sourcedocument')),
            ],
        ),
    ]
