# Generated by Django 5.2.1 on 2026-05-27 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0010_alter_accountmappingrule_unique_together_and_more'),
        ('tools', '0024_remove_adjustment_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('asset_type', models.CharField(choices=[('FURNITURE', 'Furniture & fittings 家具与设备'), ('VEHICLE', 'Motor and Vehicle 机动车辆'), ('EQUIPMENT', 'Machinery & Equipment 机械设备')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active 在用'), ('DISPOSED', 'Disposed 已处置')], default='ACTIVE', max_length=20)),
                ('purchase_cost', models.DecimalField(decimal_places=2, help_text='Capitalized Cost', max_digits=12)),
                ('depreciation_start_date', models.DateField()),
                ('depreciation_method', models.CharField(choices=[('SL', 'Straight Line 直线法'), ('DB', 'Declining Balance 余额递减法')], default='SL', max_length=5)),
                ('useful_life_months', models.IntegerField(help_text='e.g. 5.5 years = 66 months')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('acc_dep_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acc_dep_acct', to='account.account')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_acct', to='account.account')),
                ('dep_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dep_exp_acct', to='account.account')),
                ('purchase', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField()),
                ('proceeds', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_book_value_at_disposal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gain_loss_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_record', to='assets.asset')),
                ('disposal_income_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_inc_acct', to='account.account')),
                ('journal_entry', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='assets.asset')),
                ('journal_entry', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.journalentry')),
            ],
        ),
    ]
