# Generated by Django 5.2.1 on 2026-06-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('FURNITURE', 'Furniture & fittings 家具与设备'), ('VEHICLE', 'Motor and Vehicle 机动车辆'), ('EQUIPMENT', 'Machinery & Equipment 机械设备'), ('OFFICE EQUIPMENT', 'Office Equipment 办公室设备'), ('COMPUTER & IT', 'Computer & IT Equipment 电脑与IT设备'), ('Building', 'Building 建筑物'), ('Renovation', 'Renovation 装修')], max_length=20),
        ),
    ]
