# Generated by Django 5.2.1 on 2026-06-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='depreciation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
