# Generated by Django 5.2.1 on 2026-06-26 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_description_and_more'),
        ('tools', '0025_historicalpurchase_debit_account_id_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vattin', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_account_id', models.IntegerField(blank=True, default=181000, null=True)),
                ('wht_debit_account_id', models.IntegerField(blank=True, null=True)),
                ('vat_debit_account_id', models.IntegerField(blank=True, null=True)),
                ('credit_account_id', models.IntegerField(blank=True, default=200000, null=True)),
                ('description', models.TextField(blank=True, help_text='e.g. commercial invoice, custom declaration, THC/DO, port charge, clearance and trucking', null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('capitalization', models.TextField(blank=True, help_text='Basis of capitalization value (e.g. vendor price, COP, prorated THC/DO...)', null=True)),
                ('payment_status', models.CharField(choices=[('Open', 'Open'), ('Prepayment', 'Prepayment'), ('Paid', 'Paid')], default='Open', max_length=50)),
                ('unreg_usd', models.FloatField(blank=True, null=True)),
                ('exempt_usd', models.FloatField(blank=True, null=True)),
                ('vat_base_usd', models.FloatField(blank=True, null=True)),
                ('vat_usd', models.FloatField(blank=True, null=True)),
                ('wht_usd', models.FloatField(blank=True, null=True)),
                ('total_usd', models.FloatField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='capitalization_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.capitalization'),
        ),
    ]
