# Generated by Django 5.2.1 on 2026-06-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_capitalization_asset_capitalization_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalization',
            name='vat_debit_account_id',
            field=models.IntegerField(blank=True, default=115010, null=True),
        ),
        migrations.AlterField(
            model_name='capitalization',
            name='wht_debit_account_id',
            field=models.IntegerField(blank=True, default=725420, null=True),
        ),
    ]
