# Generated by Django 5.2.1 on 2026-06-26 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_capitalization_vat_debit_account_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=255, unique=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_invoice_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_invoice_weight', models.FloatField(blank=True, default=0.0, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cdc', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('item_gross_weight_kg', models.FloatField(blank=True, default=0.0, null=True)),
                ('customs_declaration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_duty_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('special_tax_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('value_added_tax_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('auxiliary_invoice_numbers', models.TextField(blank=True, null=True)),
                ('total_freight_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_insurance_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_thc_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_port_charges_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_clearance_trucking_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('net_reimbursement_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('prorated_insurance_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('prorated_net_reimb_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('prorated_freight_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('prorated_thc_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('prorated_port_charges_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('prorated_clearance_trucking_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('capitalized_value_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
