# Generated by Django 5.2.1 on 2026-06-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
