# Generated by Django 5.2.1 on 2026-03-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0007_client_alter_purchase_date_alter_vendor_vendor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('bank_ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trans_type', models.CharField(blank=True, max_length=100, null=True)),
                ('counterparty', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_remark', models.TextField(blank=True, null=True)),
                ('debit', models.FloatField(default=0.0)),
                ('credit', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.client')),
            ],
        ),
    ]
