# Generated by Django 5.2.1 on 2026-03-14 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_cash'),
        ('tools', '0012_purchase_wht_debit_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='matched_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_payments', to='tools.purchase'),
        ),
        migrations.AddField(
            model_name='cash',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='matched_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_payments', to='tools.purchase'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.vendor'),
        ),
    ]
