# Generated by Django 5.2.1 on 2026-03-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_bank_instruction_bank_matched_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='credit_account_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='debit_account_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='credit_account_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='debit_account_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
