# Generated by Django 5.2.1 on 2026-04-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0006_bank_user_cash_user'),
        ('tools', '0017_remove_journalvoucher_credi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.vendor'),
        ),
    ]
