# Generated by Django 5.2.1 on 2026-04-15 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0007_bank_vendor'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.customer'),
        ),
    ]
