# Generated by Django 5.2.1 on 2026-04-15 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0008_bank_customer'),
        ('sale', '0002_sale_delete_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='matched_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_receipts', to='sale.sale'),
        ),
        migrations.AddField(
            model_name='cash',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.customer'),
        ),
        migrations.AddField(
            model_name='cash',
            name='matched_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipts', to='sale.sale'),
        ),
    ]
