# Generated by Django 5.2.1 on 2026-04-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0009_bank_matched_sale_cash_customer_cash_matched_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='matched_purchase_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='matched_sale_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='matched_purchase_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='matched_sale_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
