# Generated by Django 5.2.1 on 2026-04-29 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0010_bank_matched_purchase_ids_bank_matched_sale_ids_and_more'),
        ('tools', '0020_journalvoucher_user_old_user_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='matched_jv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_payments', to='tools.journalvoucher'),
        ),
        migrations.AddField(
            model_name='bank',
            name='matched_jv_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='matched_jv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_payments', to='tools.journalvoucher'),
        ),
        migrations.AddField(
            model_name='cash',
            name='matched_jv_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
