# Generated by Django 5.2.1 on 2026-06-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0012_remove_bank_client_remove_cash_client_historicalbank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='fee_account_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='fee_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cash',
            name='fee_account_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='fee_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicalbank',
            name='fee_account_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalbank',
            name='fee_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicalcash',
            name='fee_account_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcash',
            name='fee_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
