# Generated by Django 5.2.1 on 2026-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('tools', '0013_purchase_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='authorized_profiles', to='tools.client'),
        ),
    ]
