# Generated by Django 5.2.1 on 2026-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('accounting', 'Accounting Advisory'), ('audit', 'Audit Advisory'), ('tax', 'Tax Advisory')], max_length=100),
        ),
    ]
