# Generated by Django 5.2.1 on 2026-04-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0017_remove_journalvoucher_credi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_client', to='tools.client')),
            ],
            options={
                'unique_together': {('client', 'customer_id')},
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_account_id', models.IntegerField(blank=True, null=True)),
                ('vat_output_id', models.IntegerField(blank=True, null=True)),
                ('credit_account_id', models.IntegerField(blank=True, default=200000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('Open', 'Open'), ('Prepayment', 'Prepayment'), ('Paid', 'Paid')], default='Open', max_length=50)),
                ('vat_base_usd', models.FloatField(blank=True, null=True)),
                ('vat_usd', models.FloatField(blank=True, null=True)),
                ('total_usd', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_client', to='tools.client')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.customer')),
            ],
        ),
    ]
