# Generated by Django 5.2.1 on 2026-03-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vattin', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('non_vat_non_tax_payer_usd', models.FloatField(blank=True, null=True)),
                ('non_vat_tax_payer_usd', models.FloatField(blank=True, null=True)),
                ('local_purchase_usd', models.FloatField(blank=True, null=True)),
                ('local_purchase_vat_usd', models.FloatField(blank=True, null=True)),
                ('total_usd', models.FloatField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
