# Generated by Django 5.2.1 on 2026-03-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Petty (hand-written)', 'Petty (hand-written)'), ('Petty (print)', 'Petty (print)'), ('GDT', 'GDT'), ('Receipt', 'Receipt'), ('Commercial Invoice', 'Commercial Invoice'), ('Tax Invoice', 'Tax Invoice'), ('Bank Slip', 'Bank Slip')], max_length=50)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('KHR', 'KHR')], default='USD', max_length=3)),
                ('amount', models.FloatField()),
                ('page', models.CharField(max_length=50)),
            ],
        ),
    ]
