# Generated by Django 5.2.1 on 2026-03-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_pages', models.IntegerField()),
                ('flash_cost', models.FloatField(default=0.0)),
                ('pro_cost', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='company',
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
