# Generated by Django 5.2.1 on 2026-03-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_aicostlog_vendor_delete_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
