# Generated by Django 5.2.1 on 2026-03-09 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_purchase_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.vendor'),
        ),
    ]
