# Generated by Django 5.2.1 on 2026-03-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_remove_purchase_vendor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='batch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
