# Generated by Django 5.2.1 on 2026-03-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_purchase_batch_purchase_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, help_text='e.g., CCKT', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.client'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='tools.client'),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('client', 'vendor_id')},
        ),
    ]
