# Generated by Django 5.2.1 on 2026-03-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_client_alter_purchase_date_alter_vendor_vendor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicostlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
