# Generated by Django 5.2.1 on 2026-03-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_aicostlog_created_at_purchase_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='credit_account_id',
            field=models.IntegerField(blank=True, default=200000, null=True),
        ),
    ]
