# Generated by Django 5.2.1 on 2026-03-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_purchase_credit_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='local_purchase_usd',
            new_name='exempt_usd',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='local_purchase_vat_usd',
            new_name='unreg_usd',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='non_vat_non_tax_payer_usd',
            new_name='vat_base_usd',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='non_vat_tax_payer_usd',
            new_name='vat_usd',
        ),
    ]
