# Generated by Django 5.2.1 on 2026-03-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_rename_local_purchase_usd_purchase_exempt_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='vat_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='wht_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
