# Generated by Django 5.2.1 on 2026-03-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_purchase_vat_account_id_purchase_wht_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='wht_debit_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
