# Generated by Django 5.2.1 on 2026-03-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_purchase_wht_debit_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Prepayment', 'Prepayment'), ('Paid', 'Paid')], default='Open', max_length=50),
        ),
    ]
