# Generated by Django 5.2.1 on 2026-04-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_journalvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvoucher',
            name='account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
