# Generated by Django 5.2.1 on 2026-04-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_journalvoucher_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalvoucher',
            name='credi',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='payment_status',
        ),
    ]
