# Generated by Django 5.2.1 on 2026-04-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_remove_journalvoucher_credi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalvoucher',
            name='account_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
