# Generated by Django 5.2.1 on 2026-04-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_alter_journalvoucher_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvoucher',
            name='payment_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Prepayment', 'Prepayment'), ('Paid', 'Paid')], default='Open', max_length=50),
        ),
    ]
