# Generated by Django 5.2.1 on 2026-05-04 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_sale_delete_revenue'),
        ('tools', '0021_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.customer'),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.vendor'),
        ),
    ]
