# Generated by Django 5.2.1 on 2026-06-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0024_remove_adjustment_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='debit_account_id_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='debit_account_id_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='debit_amount_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='debit_amount_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='debit_desc_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='debit_desc_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='debit_account_id_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='debit_account_id_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='debit_amount_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='debit_amount_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='debit_desc_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='debit_desc_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
